### ISSUE TITLE
Test suite errors without compiling/running 

### ISSUE THREAD

**Issue by cgewecke** [OpenZeppelin/zeppelin-solidity#207]
My environment:
+ OSX 10.11.5
+ Node 6.9.1

Running `npm test` on a fresh clone of zeppelin-solidity after a successful `npm install`, I get the following error:

```
gewecke:zeppelin-solidity user$ npm test

> zeppelin-solidity@1.0.4 test /Users/user/Sites/zeppelin-solidity
> scripts/test.sh

Connection to localhost port 8545 [tcp/*] succeeded!
Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (/Users/user/Sites/zeppelin-solidity/node_modules/web3/lib/web3/errors.js:35:16)
    at XMLHttpRequest.request.onreadystatechange (/Users/user/Sites/zeppelin-solidity/node_modules/web3/lib/web3/httpprovider.js:115:32)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/user/Sites/zeppelin-solidity/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/Users/user/Sites/zeppelin-solidity/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpRequestError (/Users/user/Sites/zeppelin-solidity/node_modules/xhr2/lib/xhr2.js:544:12)
    at ClientRequest.<anonymous> (/Users/user/Sites/zeppelin-solidity/node_modules/xhr2/lib/xhr2.js:414:24)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
```

These tests ran perfectly for me as recently as 8 days ago. I see one commit since then but it passes CI.  

Would really just like to know if this issue is reproducible or something weird on my end.

**Comment by frangio** [comment]
This error usually means testrpc isn't running. However, it looks like in your case there is something running in the usual port. Could you check if that's the case?

**Comment by cgewecke** [comment]
I can  testrpc from the command line - I would usually get an error there if there was a background instance I think. I also see this line
```
Connection to localhost port 8545 [tcp/*] succeeded!
```
in zeppelin's output.

**Comment by frangio** [comment]
I actually have no idea what's printing the "connection succeded" message. I can't reproduce the problem either.

**Comment by cgewecke** [comment]
Ok thanks @frangio! That's helpful. Closing.

**Comment by frangio** [comment]
Have you been able to fix this issue?

**Comment by cgewecke** [comment]
Yes, sorry. Somehow didn't click close. *Definitely* closing.
