### ISSUE TITLE
require() in contracts constructor throws invalid opcode except in internal tests

### ISSUE THREAD

**Issue by fabienb4** [OpenZeppelin/zeppelin-solidity#294]
### Tested with:
ethereumjs-testrpc: v4.0.1 (ganache-core: 1.0.1)
truffle: 3.3.2
zeppelin-solidity: 1.1.0

### Reproduction: 

`sudo npm install -g truffle`
`mkdir test`
`cd test`
`truffle init`
`npm install zeppelin-solidity`
`touch contracts/TestCrowdsale.sol`

**TestCrowdsale.sol**  (exactly as the zeppelin-solidity mock except for the import)
```solidity
pragma solidity ^0.4.11;


import 'zeppelin-solidity/contracts/crowdsale/RefundableCrowdsale.sol';


contract TestCrowdsale is RefundableCrowdsale {

  function TestCrowdsale (
    uint256 _startBlock,
    uint256 _endBlock,
    uint256 _rate,
    address _wallet,
    uint256 _goal
  )
    Crowdsale(_startBlock, _endBlock, _rate, _wallet)
    RefundableCrowdsale(_goal)
  {
  }

}
```

**deploy_contracts.js**
```diff
diff --git a/2_deploy_contracts.js b/2_deploy_contracts.js
index b3dc3e9..e8f84a4 100644
--- a/2_deploy_contracts.js
+++ b/2_deploy_contracts.js
@@ -1,8 +1,10 @@
 var ConvertLib = artifacts.require("./ConvertLib.sol");
 var MetaCoin = artifacts.require("./MetaCoin.sol");
+var TestCrowdsale = artifacts.require("./TestCrowdsale.sol");
 
 module.exports = function(deployer) {
   deployer.deploy(ConvertLib);
   deployer.link(ConvertLib, MetaCoin);
   deployer.deploy(MetaCoin);
+  deployer.deploy(TestCrowdsale);
 };
```

`truffle test` (you will need testrpc running for this part)

```
Compiling ./contracts/ConvertLib.sol...
Compiling ./contracts/MetaCoin.sol...
Compiling ./contracts/Migrations.sol...
Compiling ./contracts/TestCrowdsale.sol...
Compiling ./test/TestMetacoin.sol...
Compiling truffle/Assert.sol...
Compiling truffle/DeployedAddresses.sol...
Compiling zeppelin-solidity/contracts/crowdsale/Crowdsale.sol...
Compiling zeppelin-solidity/contracts/crowdsale/FinalizableCrowdsale.sol...
Compiling zeppelin-solidity/contracts/crowdsale/RefundVault.sol...
Compiling zeppelin-solidity/contracts/crowdsale/RefundableCrowdsale.sol...
Compiling zeppelin-solidity/contracts/math/SafeMath.sol...
Compiling zeppelin-solidity/contracts/ownership/Ownable.sol...
Compiling zeppelin-solidity/contracts/token/BasicToken.sol...
Compiling zeppelin-solidity/contracts/token/ERC20.sol...
Compiling zeppelin-solidity/contracts/token/ERC20Basic.sol...
Compiling zeppelin-solidity/contracts/token/MintableToken.sol...
Compiling zeppelin-solidity/contracts/token/StandardToken.sol...
Error: VM Exception while processing transaction: invalid opcode
    at Object.InvalidResponse (/usr/lib/node_modules/truffle/build/cli.bundled.js:36886:16)
    at /usr/lib/node_modules/truffle/build/cli.bundled.js:206712:36
    at XMLHttpRequest.request.onreadystatechange (/usr/lib/node_modules/truffle/build/cli.bundled.js:205491:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/lib/node_modules/truffle/build/cli.bundled.js:207364:18)
    at XMLHttpRequest._setReadyState (/usr/lib/node_modules/truffle/build/cli.bundled.js:207654:12)
    at XMLHttpRequest._onHttpResponseEnd (/usr/lib/node_modules/truffle/build/cli.bundled.js:207809:12)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/truffle/build/cli.bundled.js:207769:24)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
```

Now modifying the zeppelin-solidity Crowdsale & RefundVault contracts:
```diff
diff --git a/Crowdsale.sol b/Crowdsale.sol
index bee1efd..e3832df 100644
--- a/Crowdsale.sol
+++ b/Crowdsale.sol
@@ -36,15 +36,15 @@ contract Crowdsale {
    * @param beneficiary who got the tokens
    * @param value weis paid for purchase
    * @param amount amount of tokens purchased
-   */ 
+   */
   event TokenPurchase(address indexed purchaser, address indexed beneficiary, uint256 value, uint256 amount);
 
 
   function Crowdsale(uint256 _startBlock, uint256 _endBlock, uint256 _rate, address _wallet) {
-    require(_startBlock >= block.number);
-    require(_endBlock >= _startBlock);
-    require(_rate > 0);
-    require(_wallet != 0x0);
+    //require(_startBlock >= block.number);
+    //require(_endBlock >= _startBlock);
+    //require(_rate > 0);
+    //require(_wallet != 0x0);
 
     token = createTokenContract();
     startBlock = _startBlock;
```

```diff
diff --git a/RefundVault.sol b/RefundVault.sol
index cc92ff9..8c8daf0 100644
--- a/RefundVault.sol
+++ b/RefundVault.sol
@@ -23,7 +23,7 @@ contract RefundVault is Ownable {
   event Refunded(address indexed beneficiary, uint256 weiAmount);
 
   function RefundVault(address _wallet) {
-    require(_wallet != 0x0);
+    //require(_wallet != 0x0);
     wallet = _wallet;
     state = State.Active;
   }
```

`truffle test` (you will need testrpc running for this part)

```
Compiling ./contracts/ConvertLib.sol...
Compiling ./contracts/MetaCoin.sol...
Compiling ./contracts/Migrations.sol...
Compiling ./contracts/TestCrowdsale.sol...
Compiling ./test/TestMetacoin.sol...
Compiling truffle/Assert.sol...
Compiling truffle/DeployedAddresses.sol...
Compiling zeppelin-solidity/contracts/crowdsale/Crowdsale.sol...
Compiling zeppelin-solidity/contracts/crowdsale/FinalizableCrowdsale.sol...
Compiling zeppelin-solidity/contracts/crowdsale/RefundVault.sol...
Compiling zeppelin-solidity/contracts/crowdsale/RefundableCrowdsale.sol...
Compiling zeppelin-solidity/contracts/math/SafeMath.sol...
Compiling zeppelin-solidity/contracts/ownership/Ownable.sol...
Compiling zeppelin-solidity/contracts/token/BasicToken.sol...
Compiling zeppelin-solidity/contracts/token/ERC20.sol...
Compiling zeppelin-solidity/contracts/token/ERC20Basic.sol...
Compiling zeppelin-solidity/contracts/token/MintableToken.sol...
Compiling zeppelin-solidity/contracts/token/StandardToken.sol...


  TestMetacoin
    ✓ testInitialBalanceUsingDeployedContract (92ms)
    ✓ testInitialBalanceWithNewMetaCoin (71ms)

  Contract: MetaCoin
    ✓ should put 10000 MetaCoin in the first account (50ms)
    ✓ should call a function that depends on a linked library (74ms)
    ✓ should send coin correctly (149ms)


  5 passing (1s)

```

**I ran the internal zeppelin-solidity tests and they work just fine without modifications...**
I did not investigate the issue beyond that, out of time..!

PS: `./scripts/test.sh` now references an invalid path for truffle cli:
`./node_modules/truffle/cli.js`
`./node_modules/truffle/build/cli.bundled.js`

**Comment by maraoz** [comment]
@fabienb4 This is because you're not passing any constructor arguments when deploying the TestCrowdsale contract! 

You should do:
```
...
deployer.deploy(TestCrowdsale, startBlock, endBlock, ...);
...
```

**Comment by fabienb4** [comment]
Geez, I knew I needed some sleep... Nevermind, thanks ;-)
