### ISSUE TITLE
Broken test coverage generation

### ISSUE THREAD

**Issue by jwojciechowski** [OpenZeppelin/zeppelin-solidity#298]
From logs of [the last build](https://travis-ci.org/OpenZeppelin/zeppelin-solidity/builds/250779298), I've checked it's been broken for a long time ([a build from a month ago](https://travis-ci.org/OpenZeppelin/zeppelin-solidity/builds/239976996) )

Launching test command (this can take a few seconds)...
Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (/home/travis/build/OpenZeppelin/zeppelin-solidity/node_modules/web3/lib/web3/errors.js:35:16)
    at XMLHttpRequest.request.onreadystatechange (/home/travis/build/OpenZeppelin/zeppelin-solidity/node_modules/web3/lib/web3/httpprovider.js:115:32)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/travis/build/OpenZeppelin/zeppelin-solidity/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/home/travis/build/OpenZeppelin/zeppelin-solidity/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpRequestError (/home/travis/build/OpenZeppelin/zeppelin-solidity/node_modules/xhr2/lib/xhr2.js:544:12)
    at ClientRequest.<anonymous> (/home/travis/build/OpenZeppelin/zeppelin-solidity/node_modules/xhr2/lib/xhr2.js:414:24)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
Cleaning up...
    There was an error generating coverage. Possible reasons include:
    1. Another application is using port 8555 
    2. Truffle crashed because your tests errored
    
  Error: ENOENT: no such file or directory, open './allFiredEvents'
Exiting without generating coverage...

**Comment by jwojciechowski** [comment]
I've just noticed that this issue is touched in the discussion about [coverage reports](https://github.com/OpenZeppelin/zeppelin-solidity/issues/291).
Feel free to merge the issues.

**Comment by maraoz** [comment]
Closing as duplicate. Thanks for reporting
