### ISSUE TITLE
Issue installing zeppelin-solidity

### ISSUE THREAD

**Issue by prahaladbelavadi** [OpenZeppelin/zeppelin-solidity#461]
Error: while trying to install zeppelin-solidity

```
$ npm install zeppelin-solidity

> scrypt@6.0.3 preinstall C:\Users\praha\node_modules\scrypt
> node node-scrypt-preinstall.js


> scrypt@6.0.3 install C:\Users\praha\node_modules\scrypt
> node-gyp rebuild


C:\Users\praha\node_modules\scrypt>if not defined npm_config_node_gyp (node "C:\Users\praha\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Warning: Missing input files:
C:\Users\praha\node_modules\scrypt\build\..\scrypt\win\include\config.h
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Users\praha\node_modules\scrypt\build\copied_files.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
C:\Users\praha\node_modules\scrypt\build\scrypt_wrapper.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\praha\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\praha\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\praha\node_modules\scrypt
gyp ERR! node -v v6.11.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\praha\package.json'
npm WARN praha No description
npm WARN praha No repository field.
npm WARN praha No README data
npm WARN praha No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\praha\AppData\Roaming\npm-cache\_logs\2017-09-21T09_03_34_243Z-debug.log

```
![image](https://user-images.githubusercontent.com/16673094/30688215-3089a11e-9edb-11e7-91a7-0c49cfa6461b.png)

References:
- [Node-gyp](https://github.com/nodejs/node-gyp/issues/1014)
- [Failed at node-gyp-rebuild](https://github.com/barrysteyn/node-scrypt/issues/135)
- [C++ compiler missing](https://stackoverflow.com/questions/39358117/npm-cannot-install-truffle-on-windows)
- [node-gyp](https://github.com/nodejs/node-gyp/issues/809)
- [node-gyp](https://github.com/barrysteyn/node-scrypt/issues/88)

**Comment by prahaladbelavadi** [comment]
Moving over to linux.
Installing 10 Gb of bloated software isn't necessary.
Use an alternative C++ compiler instead or an environment that has it

**Comment by uluhonolulu** [comment]
Installing VC++ might solve it.
