### ISSUE TITLE
Can't step through transaction during debug

### ISSUE THREAD

**Issue by brianedelman** [OpenZeppelin/zeppelin-solidity#520]
Using node v8.4.0
truffle 4 beta 2

I create a new contract in the develop console which runs successfully, and then debug the transaction. The debugger runs and shows me the first line of code, but when I try to do any further action (i.e. step through the code), it fails with a trace and instruction mismatch error.

Below is the process.

```Connected to exiting Truffle Develop session at http://localhost:9545/

truffle(develop)> Ticket.new("name")
TruffleContract {
  constructor:
   { [Function: TruffleContract]
     _static_methods:
      { setProvider: [Function: setProvider],
        new: [Function: new],
        at: [Function: at],
        deployed: [Function: deployed],
        defaults: [Function: defaults],
        hasNetwork: [Function: hasNetwork],
        isDeployed: [Function: isDeployed],
        detectNetwork: [Function: detectNetwork],
        setNetwork: [Function: setNetwork],
        resetAddress: [Function: resetAddress],
        link: [Function: link],
        clone: [Function: clone],
        addProp: [Function: addProp],
        toJSON: [Function: toJSON] },
     _properties:
      { contract_name: [Object],
        contractName: [Object],
        abi: [Object],
        network: [Function: network],
        networks: [Function: networks],
        address: [Object],
        links: [Function: links],
        events: [Function: events],
        binary: [Function: binary],
        deployedBinary: [Function: deployedBinary],
        unlinked_binary: [Object],
        bytecode: [Object],
        deployedBytecode: [Object],
        sourceMap: [Object],
        deployedSourceMap: [Object],
        source: [Object],
        sourcePath: [Object],
        ast: [Object],
        schema_version: [Function: schema_version],
        schemaVersion: [Function: schemaVersion],
        updated_at: [Function: updated_at],
        updatedAt: [Function: updatedAt] },
     _property_values: {},
     _json:
      { contractName: 'Ticket',
        abi: [Array],
        bytecode: '0x60606040523415600e57600080fd5b6040516020806100c3833981016040528080516000555050608f806100346000396000f300606060405263ffffffff7c010000000000000000000000000000000000000000000000000000000060003504166306fdde038114603b57600080fd5b3415604557600080fd5b604b605d565b60405190815260200160405180910390f35b600054815600a165627a7a7230582041549c81fdd3a26b560f5c07fc72ae1bb9bbdf7b3edf8a1a7eb383e46366c1af0029',
        deployedBytecode: '0x606060405263ffffffff7c010000000000000000000000000000000000000000000000000000000060003504166306fdde038114603b57600080fd5b3415604557600080fd5b604b605d565b60405190815260200160405180910390f35b600054815600a165627a7a7230582041549c81fdd3a26b560f5c07fc72ae1bb9bbdf7b3edf8a1a7eb383e46366c1af0029',
        sourceMap: '186:107:4:-;;;230:61;;;;;;;;;;;;;;;;;;;;;;274:4;:12;-1:-1:-1;;186:107:4;;;;;;',
        deployedSourceMap: '186:107:4:-;;;;;;;;;;;;;;;;;206:19;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::o',
        source: 'pragma solidity 0.4.17;\n\nimport \'zeppelin-solidity/contracts/token/MintableToken.sol\';\n\n//Ticket is a mintable token. Event can call ticket to create a new Token(ticket) for each event.\ncontract Ticket {\n  bytes32 public name;\n\n  function Ticket(bytes32 _name) public {\n    name = _name;\n  }\n}\n',
        sourcePath: '/Users/brianedelman/Coding/projects/tickets2/contracts/Ticket.sol',
        ast: [Object],
        networks: [Object],
        schemaVersion: '1.0.0',
        updatedAt: '2017-10-27T16:27:28.005Z' },
     setProvider: [Function: bound setProvider],
     new: [Function: bound new],
     at: [Function: bound at],
     deployed: [Function: bound deployed],
     defaults: [Function: bound defaults],
     hasNetwork: [Function: bound hasNetwork],
     isDeployed: [Function: bound isDeployed],
     detectNetwork: [Function: bound detectNetwork],
     setNetwork: [Function: bound setNetwork],
     resetAddress: [Function: bound resetAddress],
     link: [Function: bound link],
     clone: [Function: bound clone],
     addProp: [Function: bound addProp],
     toJSON: [Function: bound toJSON],
     web3:
      Web3 {
        _requestManager: [Object],
        currentProvider: [Object],
        eth: [Object],
        db: [Object],
        shh: [Object],
        net: [Object],
        personal: [Object],
        bzz: [Object],
        settings: [Object],
        version: [Object],
        providers: [Object],
        _extend: [Object] },
     class_defaults:
      { from: '0x64a6b92b99e793d9a343a560e39697fcb422ae90',
        gas: 4712388,
        gasPrice: 100000000000 },
     currentProvider:
      HttpProvider {
        host: 'http://localhost:9545/',
        timeout: 0,
        user: undefined,
        password: undefined,
        send: [Function],
        sendAsync: [Function],
        _alreadyWrapped: true },
     network_id: '4447' },
  abi:
   [ { constant: true,
       inputs: [],
       name: 'name',
       outputs: [Array],
       payable: false,
       stateMutability: 'view',
       type: 'function' },
     { inputs: [Array],
       payable: false,
       stateMutability: 'nonpayable',
       type: 'constructor' } ],
  contract:
   Contract {
     _eth:
      Eth {
        _requestManager: [Object],
        getBalance: [Object],
        getStorageAt: [Object],
        getCode: [Object],
        getBlock: [Object],
        getUncle: [Object],
        getCompilers: [Object],
        getBlockTransactionCount: [Object],
        getBlockUncleCount: [Object],
        getTransaction: [Object],
        getTransactionFromBlock: [Object],
        getTransactionReceipt: [Object],
        getTransactionCount: [Object],
        call: [Object],
        estimateGas: [Object],
        sendRawTransaction: [Object],
        signTransaction: [Object],
        sendTransaction: [Object],
        sign: [Object],
        compile: [Object],
        submitWork: [Object],
        getWork: [Object],
        coinbase: [Getter],
        getCoinbase: [Object],
        mining: [Getter],
        getMining: [Object],
        hashrate: [Getter],
        getHashrate: [Object],
        syncing: [Getter],
        getSyncing: [Object],
        gasPrice: [Getter],
        getGasPrice: [Object],
        accounts: [Getter],
        getAccounts: [Object],
        blockNumber: [Getter],
        getBlockNumber: [Object],
        protocolVersion: [Getter],
        getProtocolVersion: [Object],
        iban: [Object],
        sendIBANTransaction: [Function: bound transfer] },
     transactionHash: '0x84ff11e5c596729495c03f1645febf67014af0fc1105f9218ee56a3f37944f57',
     address: '0x2b04839502b528d29a7eb7c614c8c64c8bacc5c9',
     abi: [ [Object], [Object] ],
     name:
      { [Function: bound ]
        request: [Function: bound ],
        call: [Function: bound ],
        sendTransaction: [Function: bound ],
        estimateGas: [Function: bound ],
        getData: [Function: bound ],
        '': [Circular] },
     allEvents: [Function: bound ] },
  name:
   { [Function]
     call: [Function],
     sendTransaction: [Function],
     request: [Function: bound ],
     estimateGas: [Function] },
  sendTransaction: [Function],
  send: [Function],
  allEvents: [Function: bound ],
  address: '0x2b04839502b528d29a7eb7c614c8c64c8bacc5c9',
  transactionHash: '0x84ff11e5c596729495c03f1645febf67014af0fc1105f9218ee56a3f37944f57' }
truffle(develop)> debug 0x84ff11e5c596729495c03f1645febf67014af0fc1105f9218ee56a3f37944f57
Gathering transaction data...

Addresses affected:
  0x2b04839502b528d29a7eb7c614c8c64c8bacc5c9 - Ticket

Commands:
(enter) last command entered (step next)
(o) step over, (i) step into, (u) step out, (n) step next
(;) step instruction, (p) print instruction, (h) print this help, (q) quit


Ticket.sol | 0x2b04839502b528d29a7eb7c614c8c64c8bacc5c9:

4:
5: //Ticket is a mintable token. Event can call ticket to create a new Token(ticket) for each event.
6: contract Ticket {
   ^^^^^^^^^^^^^^^^

debug(develop:0x84ff11e5...)> i
Error: Trace and instruction mismatch.

trace {
  "depth": 0,
  "error": "",
  "gas": 4648350,
  "gasCost": 12,
  "memory": [
    "0000000000000000000000000000000000000000000000000000000000000000",
    "0000000000000000000000000000000000000000000000000000000000000000",
    "0000000000000000000000000000000000000000000000000000000000000060"
  ],
  "op": "CALLVALUE",
  "pc": 5,
  "stack": [],
  "storage": {}
}
instruction {
  "name": "PUSH4",
  "fee": 3,
  "in": 0,
  "out": 1,
  "dynamic": false,
  "pc": 5,
  "pushData": "0xffffffff",
  "index": 3,
  "jump": "-",
  "start": 186,
  "length": 107,
  "range": {
    "start": {
      "line": 5,
      "column": 0
    },
    "end": {
      "line": 12,
      "column": 0
    }
  }
}

This is likely due to a bug in the debugger. Please file an issue on the Truffle issue tracker and provide as much information about your code and transaction as possible.

Fatal Error: See above.
    at Debugger.advance (/Users/brianedelman/.nvm/versions/node/v8.4.0/lib/node_modules/truffle/build/cli.bundled.js:308637:13)
    at Debugger.step (/Users/brianedelman/.nvm/versions/node/v8.4.0/lib/node_modules/truffle/build/cli.bundled.js:308669:10)
    at Debugger.stepOver (/Users/brianedelman/.nvm/versions/node/v8.4.0/lib/node_modules/truffle/build/cli.bundled.js:308795:31)
    at Debugger.stepInto (/Users/brianedelman/.nvm/versions/node/v8.4.0/lib/node_modules/truffle/build/cli.bundled.js:308709:17)
    at Object.interpreter (/Users/brianedelman/.nvm/versions/node/v8.4.0/lib/node_modules/truffle/build/cli.bundled.js:301079:22)
    at ReplManager.interpret (/Users/brianedelman/.nvm/versions/node/v8.4.0/lib/node_modules/truffle/build/cli.bundled.js:188429:18)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:440:10)
    at emitOne (events.js:115:13)
```

NOTE: For testing purposes I deleted my contracts folder in the build directory, compiled everything again, migrated again just for good measure and then did this process. Additionally I made sure I was doing it with a contract that does bare minimum work. Below is the function for reference.

```contract Ticket {
  bytes32 public name;

  function Ticket(bytes32 _name) public {
    name = _name;
  }
}
```

**Comment by maraoz** [comment]
Maybe this should be an issue in the Truffle repo?
