### ISSUE TITLE
Unable to test Zeppelin contracts

### ISSUE THREAD

**Issue by shoenseiwaso** [OpenZeppelin/zeppelin-solidity#536]
I wasn't able to find any documentation on how to run `truffle test` against the zeppelin-solidity smart contracts. I've tried several variations of the following with no luck:

```sh
$ npm init  # accepted all defaults
$ truffle init
$ npm install zeppelin-solidity
$ truffle test
Using network 'test'.
  0 passing (0ms)
$ truffle test test/Pausable.js
Using network 'test'.

Error: Could not find artifacts for helpers/PausableMock.sol from any sources
    at Resolver.require (/Users/abc/.nvm/versions/node/v8.4.0/lib/node_modules/truffle/build/cli.bundled.js:69108:9)
    at TestResolver.require (/Users/abc/.nvm/versions/node/v8.4.0/lib/node_modules/truffle/build/cli.bundled.js:201629:30)
    at Object.require (/Users/abc/.nvm/versions/node/v8.4.0/lib/node_modules/truffle/build/cli.bundled.js:320215:32)
    at Object.<anonymous> (/Users/abc/tmp/node_modules/zeppelin-solidity/test/Pausable.js:4:32)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)

$ scripts/test.sh
Starting our own testrpc instance
Error: No network specified. Cannot determine current network.
    at Object.detect (/Users/abc/tmp/node_modules/zeppelin-solidity/node_modules/truffle/build/cli.bundled.js:58658:23)
    at /Users/abc/tmp/node_modules/zeppelin-solidity/node_modules/truffle/build/cli.bundled.js:209177:21
    at /Users/abc/tmp/node_modules/zeppelin-solidity/node_modules/truffle/build/cli.bundled.js:91903:7
    at FSReqWrap.oncomplete (fs.js:135:15)

$ scripts/test.sh --network development
Starting our own testrpc instance
Unknown network "development". See your Truffle configuration file for available networks.
$ 
```

My environment:
```
$ npm version
{ 'zeppelin-solidity': '1.3.0',
  npm: '5.5.1',
  ares: '1.10.1-DEV',
  cldr: '31.0.1',
  http_parser: '2.7.0',
  icu: '59.1',
  modules: '57',
  nghttp2: '1.22.0',
  node: '8.4.0',
  openssl: '1.0.2l',
  tz: '2017b',
  unicode: '9.0',
  uv: '1.13.1',
  v8: '6.0.286.52',
  zlib: '1.2.11' }

$ truffle version
Truffle v4.0.1 (core: 4.0.1)
Solidity v0.4.18 (solc-js)
```

**Comment by frangio** [comment]
Hi @shoenseiwaso, try running `npm test`.

**Comment by shoenseiwaso** [comment]
Thanks @frangio! That worked. Can you help me understand why `npm test` and not `truffle test`?

**Comment by frangio** [comment]
Yeah sure! `npm test` runs our [`scripts/test.sh`](https://github.com/OpenZeppelin/zeppelin-solidity/blob/8e01dd14f9211239213ae7bd4c6af92dd18d4ab7/scripts/test.sh) script, which handles starting `testrpc`. This might not be necessary anymore with Truffle 4.

**Comment by shoenseiwaso** [comment]
Thanks! Appreciate the pointers.
