### ISSUE TITLE
migrate tests to async/await pattern

### ISSUE THREAD

**Issue by maraoz** [OpenZeppelin/zeppelin-solidity#57]
See: https://github.com/federicobond/ethereum-paypub/blob/d8abdcb118e3c75203f44f5097ca2a878f8a77a8/test/paypub.js#L21

Thanks @federicobond for idea

**Comment by sogoiii** [comment]
I'm working on this. Oddly enough, I can run each individual file with `truffle test ./test/Claimable.js` successfully. But When I do `truffle test`, it fails inconsistently. By that i mean, on each run, i get a different set of errors.

**Comment by maraoz** [comment]
@sogoiii want to share the errors you're getting? maybe we can help

**Comment by maraoz** [comment]
BTW, I know several people are working on this. You shouldn't aim at migrating ALL tests to this pattern. PRs that migrate just one test file are good enough :)

**Comment by sogoiii** [comment]
@maraoz good to know. Ill make a pull request soon enough. 

I think this is the root error. Granted it happens on different contracts when i do `npm test` 

```

  1) Contract: Claimable "before all" hook: prepare suite:
     Uncaught Error: the tx doesn't have the correct nonce. account has nonce of: 0 tx has nonce of: 3
    at runCall (/Users/angellopozo/.nvm/versions/node/v4.2.0/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-vm/lib/runTx.js:101:10)
    at /Users/angellopozo/.nvm/versions/node/v4.2.0/lib/node_modules/ethereumjs-testrpc/node_modules/async/lib/async.js:718:13
    at Immediate.iterate [as _onImmediate] (/Users/angellopozo/.nvm/versions/node/v4.2.0/lib/node_modules/ethereumjs-testrpc/node_modules/async/lib/async.js:262:13)
    at processImmediate [as _immediateCallback] (timers.js:368:17)
  Error: Error: the tx doesn't have the correct nonce. account has nonce of: 0 tx has nonce of: 3
      at runCall (/Users/angellopozo/.nvm/versions/node/v4.2.0/lib/node_modules/ethereumjs-testrpc/node_modules/ethereumjs-vm/lib/runTx.js:101:10)
      at /Users/angellopozo/.nvm/versions/node/v4.2.0/lib/node_modules/ethereumjs-testrpc/node_modules/async/lib/async.js:718:13
      at Immediate.iterate [as _onImmediate] (/Users/angellopozo/.nvm/versions/node/v4.2.0/lib/node_modules/ethereumjs-testrpc/node_modules/async/lib/async.js:262:13)
      at Object.module.exports.InvalidResponse (node_modules/ether-pudding/node_modules/web3/lib/web3/errors.js:35:16)
      at node_modules/ether-pudding/node_modules/web3/lib/web3/requestmanager.js:86:36
      at null.request.onreadystatechange (node_modules/web3/lib/web3/httpprovider.js:114:13)
      at null.dispatchEvent (node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
      at setState (node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
      at IncomingMessage.<anonymous> (node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
      at endReadableNT (_stream_readable.js:903:12)
[ zeppelin-solidity 2 1 ]

```

Again, if i run `truffle test ./test/Claimable` I do not get that error.

**Comment by maraoz** [comment]
@sogoiii are you using `test-rpc` or `geth`?

**Comment by sogoiii** [comment]
Im using the testrpc

**Comment by maraoz** [comment]
can you push the tests to a branch and share it here? I can take a look

**Comment by sogoiii** [comment]
Sure. I have it here on my fork ---> https://github.com/sogoiii/zeppelin-solidity/tree/async_await_tests

You have to do npm install and have babel globally.

**Comment by sogoiii** [comment]
@maraoz OK, I have a pull request for all the tests. 

They run consistently now.  --> https://github.com/OpenZeppelin/zeppelin-solidity/pull/97

The last  limitBalance didn't have an await  keyword ---> `await lb.limitedDeposit({value: amount+1})`
