### ISSUE TITLE
Crowdsale tests fail with Error: invalid address

### ISSUE THREAD

**Issue by jerry-gdd** [OpenZeppelin/zeppelin-solidity#606]
after cloning the repo and using yarn to install all dependencies, I started testrpc on localhost:8545 and tried to run the crowdsale test with `truffle test ./test/Crowdsale.test.js`

However, 7 tests are failing with `invalid address`

here is the stack trace:

` at inputAddressFormatter (/Users/myusername/.nvm/versions/node/v9.2.1/lib/node_modules/truffle/build/cli.bundled.js:34661:11)
      at inputTransactionFormatter (/Users/myusername/.nvm/versions/node/v9.2.1/lib/node_modules/truffle/build/cli.bundled.js:34487:20)
      at /Users/myusername/.nvm/versions/node/v9.2.1/lib/node_modules/truffle/build/cli.bundled.js:39565:28
      at Array.map (<anonymous>)
      at Method.formatInput (/Users/myusername/.nvm/versions/node/v9.2.1/lib/node_modules/truffle/build/cli.bundled.js:39564:32)
      at Method.toPayload (/Users/myusername/.nvm/versions/node/v9.2.1/lib/node_modules/truffle/build/cli.bundled.js:39590:23)
      at Eth.send [as sendTransaction] (/Users/myusername/.nvm/versions/node/v9.2.1/lib/node_modules/truffle/build/cli.bundled.js:39615:30)
      at SolidityFunction.sendTransaction (/Users/myusername/.nvm/versions/node/v9.2.1/lib/node_modules/truffle/build/cli.bundled.js:329617:15)
      at SolidityFunction.execute (/Users/myusername/.nvm/versions/node/v9.2.1/lib/node_modules/truffle/build/cli.bundled.js:329700:37)
      at /Users/myusername/.nvm/versions/node/v9.2.1/lib/node_modules/truffle/build/cli.bundled.js:318086:16
`
Does this have to do with updates on truffle? Because adding console.log(wallet) to the test code does show one of the wallet addresses I have in testrpc

**Comment by Shrugs** [comment]
zeppelin-solidity needs testrpc to start with some specific settings; see `scripts/test.sh`. The best way to run all of the tests is `./scripts/test.sh`.

**Comment by jerry-gdd** [comment]
Thanks, this works. Closing the issue 👍
