### ISSUE TITLE
migrate error[The contract code couldn't be stored, please check your gas amount]

### ISSUE THREAD

**Issue by leochan007** [OpenZeppelin/zeppelin-solidity#629]
use ganache for testrpc.

LCToken.sol

pragma solidity ^0.4.16;

import 'zeppelin-solidity/contracts/token/CappedToken.sol';

contract LCToken is CappedToken {
}

truffle compile is OK. 

but when execute "truffle migrate" , is show following error:

Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: The contract code couldn't be stored, please check your gas amount.
    at Object.callback (/usr/local/nodejs/lib/node_modules/truffle/build/cli.bundled.js:326931:46)
    at /usr/local/nodejs/lib/node_modules/truffle/build/cli.bundled.js:37985:25
    at /usr/local/nodejs/lib/node_modules/truffle/build/cli.bundled.js:328869:9
    at /usr/local/nodejs/lib/node_modules/truffle/build/cli.bundled.js:176178:11
    at /usr/local/nodejs/lib/node_modules/truffle/build/cli.bundled.js:324536:9
    at XMLHttpRequest.request.onreadystatechange (/usr/local/nodejs/lib/node_modules/truffle/build/cli.bundled.js:327565:7)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/nodejs/lib/node_modules/truffle/build/cli.bundled.js:176407:18)
    at XMLHttpRequest._setReadyState (/usr/local/nodejs/lib/node_modules/truffle/build/cli.bundled.js:176697:12)
    at XMLHttpRequest._onHttpResponseEnd (/usr/local/nodejs/lib/node_modules/truffle/build/cli.bundled.js:176852:12)
    at IncomingMessage.<anonymous> (/usr/local/nodejs/lib/node_modules/truffle/build/cli.bundled.js:176812:24)

**Comment by armenarmen** [comment]
Same

**Comment by Shrugs** [comment]
@leochan007 @armenarmen in this case, `CappedToken` requires an argument in its constructor; it needs to know how many tokens is the cap! It defaults to 0 (because `contract LCToken is CappedToken` actually translates to `contract LCToken is CappedToken(0)` but CappedToken has a require `require(_cap > 0);` that fails in the constructor, hence it fails on deploy.

I made a little repository that has a working example: https://github.com/Shrugs/contract-playground/blob/master/contracts/TestToken.sol
