### ISSUE TITLE
When i deploy my contract i get below mentioned error

### ISSUE THREAD

**Issue by elango501** [OpenZeppelin/zeppelin-solidity#665]
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: The contract code couldn't be stored, please check your gas amount.
    at Object.callback (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:329221:46)
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:39618:25
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:331159:9
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:175492:11
    at /usr/local/lib/node_modules/truffle/build/cli.bundled.js:314196:9
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:315621:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:70159:18)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:70449:12)
    at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:70604:12)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/cli.bundled.js:70564:24)

**Comment by spalladino** [comment]
@elango501 please ask in [stackexchange](https://ethereum.stackexchange.com/), or in the OpenZeppelin Slack if you think this issue is specific to one of the OpenZeppelin contracts. Make sure to provide the code of your contract, and the parameters you are using to deploy it, so others can help.
