### ISSUE TITLE
Deploy SampleCrowdsale.sol to ropsten testnet failed (1.7.0)

### ISSUE THREAD

**Issue by jacktang** [OpenZeppelin/zeppelin-solidity#767]
## 🎉 Description

I upgrade zeppelin to 1.7.0 and the deployment failed (see msg below) while it worked well in 1.6.0. So I try to deploy the `SampleCrowdsale` contract in `example` dir and it re-produced.

- :ballot_box_with_check: 🐛 This is a bug report. 
- [ ] 📈 This is a feature request.

## 💻 Environment

Next, we need to know what your environment looks like.

- Which version of OpenZeppelin are you using?  1.7.0
- What network are you deploying to?  Ropsten
- How are you deploying your OpenZeppelin-backed contracts?  truffle

## 📝 Details

```
$ truffle deploy --network ropsten --reset
Using network 'ropsten'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0x1429a2167e7226dabcccf1d869145752263617d7135885f3a4006b8e9bccb111
  Migrations: 0xe7fab579f4d629899fa941b1664b953ae2a3e345
Saving successful migration to network...
  ... 0xda10e2537dfa35d7a7984bb0692033f6400ad132b60e785cb9e334cbc0c70acc
Saving artifacts...
Running migration: 2_deploy_contracts.js
  Deploying SampleCrowdsale...
  ... 0xebef40bb9fb9687279189bb747b4875326730d27ba84522537b28f9d76f2d8a8
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: The contract code couldn't be stored, please check your gas amount.
    at Object.callback (/Users/jacktang/.nvm/versions/node/v8.4.0/lib/node_modules/truffle/build/cli.bundled.js:329221:46)
    at /Users/jacktang/.nvm/versions/node/v8.4.0/lib/node_modules/truffle/build/cli.bundled.js:39618:25
    at /Users/jacktang/.nvm/versions/node/v8.4.0/lib/node_modules/truffle/build/cli.bundled.js:331159:9
    at /Users/jacktang/.nvm/versions/node/v8.4.0/lib/node_modules/truffle/build/cli.bundled.js:175492:11
    at /Users/jacktang/.nvm/versions/node/v8.4.0/lib/node_modules/truffle/build/cli.bundled.js:314196:9
    at Web3ProviderEngine._inspectResponseForNewBlock (/Users/jacktang/Code/ico_maker/node_modules/web3-provider-engine/index.js:231:12)
    at /Users/jacktang/Code/ico_maker/node_modules/web3-provider-engine/index.js:131:14
    at /Users/jacktang/Code/ico_maker/node_modules/web3-provider-engine/node_modules/async/dist/async.js:473:16
    at replenish (/Users/jacktang/Code/ico_maker/node_modules/web3-provider-engine/node_modules/async/dist/async.js:993:25)
    at iterateeCallback (/Users/jacktang/Code/ico_maker/node_modules/web3-provider-engine/node_modules/async/dist/async.js:983:17)
```

* truffle.js
```
module.exports = {
  networks: {
    development: {
      host: '127.0.0.1',
      port: 8545,
      network_id: "*" // Match any network id
    },

    ropsten: {
      provider: ropstenProvider,
      // You can get the current gasLimit by running
      // truffle deploy --network rinkeby
      // truffle(rinkeby)> web3.eth.getBlock("pending", (error, result) =>
      //   console.log(result.gasLimit))
      gas: 4600000,
      gasPrice: web3.toWei("120", "gwei"),
      network_id: "3",
    },

    mainnet: {
      provider: mainNetProvider,
      gas: 4600000,
      gasPrice: web3.toWei("20", "gwei"),
      network_id: "1",
    }
  }
}
```

**Comment by jacktang** [comment]
I searched the related issue in truffle: https://github.com/trufflesuite/truffle/issues/476. The error msg is interpreted as **it will fail as Interface is not fully implemented and I'm trying to deploy myContract**

**Comment by jacktang** [comment]
The issue should be invalid, my truffle version is too old
