### ISSUE TITLE
ERC721 full impl can't migrate with Truffle

### ISSUE THREAD

**Issue by LeeDark** [OpenZeppelin/zeppelin-solidity#842]
I have used:
Truffle v4.1.3 (core: 4.1.3)
Solidity v0.4.19 (solc-js)

My Token works well with zeppelin-solidity 1.7.0, but when I change it on code from 1.8.0 I have this error:

```
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: The contract code couldn't be stored, please check your gas amount.
    at Object.callback (/usr/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/contract.js:147:1)
    at /usr/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/method.js:142:1
    at /usr/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:89:1
    at /usr/lib/node_modules/truffle/build/webpack:/~/truffle-migrate/index.js:225:1
    at /usr/lib/node_modules/truffle/build/webpack:/~/truffle-provider/wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (/usr/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (/usr/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (/usr/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

BTW 'truffle compile' works well.

Should I update Solidity compiler or Truffle?

**Comment by LeeDark** [comment]
Also I have this message into Ganache GUI:

```
[8:08:51 PM]   Transaction: 0xe7aafd81e8680a91010e97d9a338dca48786d6ed8d72e688c21adb2e26213a35
[8:08:51 PM]   Contract created: 0x345ca3e014aaf5dca488057592ee47305d9b3e10
[8:08:51 PM]   Gas usage: 53000
[8:08:51 PM]   Block Number: 3
```

**Comment by LeeDark** [comment]
When I added MyToken constructor:

```
	function MyToken() ERC721Token("MyToken", "MT") public {
	}
```
I have another error:

```
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: VM Exception while processing transaction: out of gas
    at Object.InvalidResponse (/usr/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
    at /usr/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
    at /usr/lib/node_modules/truffle/build/webpack:/~/truffle-migrate/index.js:225:1
    at /usr/lib/node_modules/truffle/build/webpack:/~/truffle-provider/wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (/usr/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (/usr/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (/usr/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

and new message into Ganache GUI:

```
[8:14:19 PM]   Transaction: 0x213c68e88912b2a354a97580a74d689695484dd4a060e28689c256ff46d2e0f3
[8:14:19 PM]   Contract created: 0x345ca3e014aaf5dca488057592ee47305d9b3e10
[8:14:19 PM]   Gas usage: 2000000
[8:14:19 PM]   Block Number: 3
```

**Comment by facuspagnuolo** [comment]
Closing then
