### ISSUE TITLE
Only transactional methods should have void return types

### ISSUE THREAD

**Issue by perlboy** [OpenZeppelin/zeppelin-solidity#874]
## 🎉 Description

Roles#check relies exclusively on require & revert causing common support library to fail during binding generation.

- [X] 🐛 This is a bug report.
- [ ] 📈 This is a feature request.

## 💻 Environment

- Which version of OpenZeppelin are you using?
master

- What network are you deploying to? testrpc? Ganache? Ropsten?
N/A, Java binding generation.

- How are you deploying your OpenZeppelin-backed contracts? truffle? Remix? Let us know!
N/A, Java binding generation.

## 📝 Details

While this is technically valid it means commonly used support libraries fail to generate bindings correctly. See web3j/web3j#324 .

## 🔢 Code To Reproduce Issue [ Good To Have ]

Please remember that with sample code it's easier to reproduce the bug and it's much faster to fix it.

```
./console/build/install/web3j/bin/web3j solidity generate Account.bin Account.abi -p io.test -o foo

              _      _____ _     _        
             | |    |____ (_)   (_)       
__      _____| |__      / /_     _   ___  
\ \ /\ / / _ \ '_ \     \ \ |   | | / _ \ 
 \ V  V /  __/ |_) |.___/ / | _ | || (_) |
  \_/\_/ \___|_.__/ \____/| |(_)|_| \___/ 
                         _/ |             
                        |__/              

Generating io.seekbrain.Account ... Exception in thread "main" java.lang.RuntimeException: Only transactional methods should have void return types
	at org.web3j.codegen.SolidityFunctionWrapper.buildConstantFunction(SolidityFunctionWrapper.java:589)
	at org.web3j.codegen.SolidityFunctionWrapper.buildFunction(SolidityFunctionWrapper.java:570)
	at org.web3j.codegen.SolidityFunctionWrapper.buildFunctionDefinitions(SolidityFunctionWrapper.java:247)
	at org.web3j.codegen.SolidityFunctionWrapper.generateJavaFiles(SolidityFunctionWrapper.java:125)
	at org.web3j.codegen.SolidityFunctionWrapper.generateJavaFiles(SolidityFunctionWrapper.java:107)
	at org.web3j.codegen.SolidityFunctionWrapperGenerator.generate(SolidityFunctionWrapperGenerator.java:123)
	at org.web3j.codegen.SolidityFunctionWrapperGenerator.main(SolidityFunctionWrapperGenerator.java:87)
	at org.web3j.codegen.SolidityFunctionWrapperGenerator.run(SolidityFunctionWrapperGenerator.java:48)
	at org.web3j.console.Runner.main(Runner.java:38)
```

## 👍 Other Information

web3j/web3j#324

Will commit proposed fix.

**Comment by frangio** [comment]
Hm, we're quite decidedly against redundant return values. We don't want to add a return value that programmers will have to always ignore, that is just confusing.

Why does web3j have this limitation? It goes against the design of the language.

**Comment by frangio** [comment]
Closing as this seems to be a bug in web3j.
