### ISSUE TITLE
Can't deploy ERC721Token 1.8.0

### ISSUE THREAD

**Issue by joelnet** [OpenZeppelin/zeppelin-solidity#880]
## 🎉 Description

Upgraded zeppelin from 1.6.0 to 1.8.0 and couldn't deploy my contracts. It was failing on the ERC721Token.

- [X] 🐛 This is a bug report.
- [ ] 📈 This is a feature request.

## 💻 Environment

Zeppelin: 1.8.0
ganache-1.1.0-x86_64
command: `truffle migrate --reset`

## 📝 Details

```
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: The contract code couldn't be stored, please check your gas amount.
    at Object.callback (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/contract.js:147:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/method.js:142:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:89:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-migrate/index.js:225:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-provider/wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

Contract:
```
pragma solidity ^0.4.13;

import "zeppelin-solidity/contracts/token/ERC721/ERC721Token.sol";
import "zeppelin-solidity/contracts/ownership/Ownable.sol";

contract ItemTokens is ERC721Token, Ownable {
   // all code commented out for testing
  // still will not deploy
}
```

**Comment by joelnet** [comment]
I put together a repo to demo the problem. https://github.com/joelnet/zeppelin-bug

1.6.0, 1.7.0 both work. But 1.8.0 has problems.

**Comment by kingjerod** [comment]
Is it possible 1.8.0 added some extra code that is costing more gas to deploy, and your maximum gas amount is less than that? Try upping your gas amount in the truffle config.

**Comment by joelnet** [comment]
same error with: 
```
module.exports = {
  networks: {
    development: {
      host: "localhost",
      port: 8545,
      network_id: "*", // Match any network id
      gas: 6000000,
    }
  }
}
```

I get `Error: Exceeds block gas limit`  when I up it any higher.

**Comment by tianyangj** [comment]
I also run into the same problem upgrading from 1.7 to 1.8.

**Comment by lamengao** [comment]
You should provide all arguments for the base constructors.

```
contract MyToken is ERC721Token, Ownable {

    function MyToken(string _name, string _symbol) ERC721Token(_name, _symbol) public {
    }

}
```

**Comment by Shrugs** [comment]
@lamengao is correct. The `ERC721Token` contract has a constructor function that requires two arguments. The deploy will fail unless those are provided. thanks @lamengao !

**Comment by tianyangj** [comment]
Yes, I can confirm it is working after I added the missing constructor function, thanks.

**Comment by joelnet** [comment]
Ahh 1.8.0 introduced a constructor.

Works great!
